export const AssetCategory: any = {
    art: {
        FieldTitle: "Upload File",
        AssetName: "Asset Name",
        AssetNamePlaceholder: "Please enter your asset name",
        AssetLink: "Url of asset (if any)",
        AssetLinkPlaceholder: "Please enter url of your asset",
        AssetInfo: "Asset Description",
        AssetInfoPlaceholder:
            "Please provide a detailed description of your asset...",
        AssetCollectionName: "Collection Name (Optional)",
        AssetButton: "Tokenise ",
    },
    "carbon credits": {
        FieldTitle: "Upload File",
        AssetName: "Asset Name",
        AssetNamePlaceholder: "Please enter your asset name",
        AssetLink: "Url of asset (if any)",
        AssetLinkPlaceholder: "Please enter url of your asset",
        AssetInfo: "Asset Description",
        AssetInfoPlaceholder:
            "Please provide a detailed description of your asset...",
        AssetCollectionName: "Collection Name (Optional)",
        AssetButton: "Tokenise ",
    },
    "event tickets": {
        FieldTitle: "Upload File",
        AssetName: "Asset Name",
        AssetNamePlaceholder: "Please enter your asset name",
        AssetLink: "Url of asset (if any)",
        AssetLinkPlaceholder: "Please enter url of your asset",
        AssetInfo: "Asset Description",
        AssetInfoPlaceholder:
            "Please provide a detailed description of your asset...",
        AssetCollectionName: "Collection Name (Optional)",
        AssetButton: "Tokenise ",
    },
    "fin. instruments": {
        FieldTitle: "Upload File",
        AssetName: "Asset Name",
        AssetNamePlaceholder: "Please enter your asset name",
        AssetLink: "Url of asset (if any)",
        AssetLinkPlaceholder: "Please enter url of your asset",
        AssetInfo: "Asset Description",
        AssetInfoPlaceholder:
            "Please provide a detailed description of your asset...",
        AssetCollectionName: "Collection Name (Optional)",
        AssetButton: "Tokenise ",
    },
    gaming: {
        FieldTitle: "Upload File",
        AssetName: "Asset Name",
        AssetNamePlaceholder: "Please enter your asset name",
        AssetLink: "Url of asset (if any)",
        AssetLinkPlaceholder: "Please enter url of your asset",
        AssetInfo: "Asset Description",
        AssetInfoPlaceholder:
            "Please provide a detailed description of your asset...",
        AssetCollectionName: "Collection Name (Optional)",
        AssetButton: "Tokenise ",
    },
    metaverse: {
        FieldTitle: "Upload File",
        AssetName: "Asset Name",
        AssetNamePlaceholder: "Please enter your asset name",
        AssetLink: "Url of asset (if any)",
        AssetLinkPlaceholder: "Please enter url of your asset",
        AssetInfo: "Asset Description",
        AssetInfoPlaceholder:
            "Please provide a detailed description of your asset...",
        AssetCollectionName: "Collection Name (Optional)",
        AssetButton: "Tokenise ",
    },

    music: {
        FieldTitle: "Upload Thumbnail File (mp4, webm)",
        AssetName: "Track Name",
        AssetNamePlaceholder: "Please enter your track name",
        AssetLink: "Url of track (if any)",
        AssetLinkPlaceholder: "Please enter url of your track",
        AssetInfo: "Track Description",
        AssetInfoPlaceholder:
            "Please provide a detailed description of your music track...",
        AssetCollectionName: "Album/Collection Name (Optional)",
        AssetButton: "Tokenise ",
    },
    "nft collection": {
        FieldTitle: "Upload File",
        AssetName: "Asset Name",
        AssetNamePlaceholder: "Please enter your asset name",
        AssetLink: "Url of asset (if any)",
        AssetLinkPlaceholder: "Please enter url of your asset",
        AssetInfo: "Asset Description",
        AssetInfoPlaceholder:
            "Please provide a detailed description of your asset...",
        AssetCollectionName: "Collection Name (Optional)",
        AssetButton: "Tokenise ",
    },
    photography: {
        FieldTitle: "Upload File",
        AssetName: "Title of Photograph",
        AssetNamePlaceholder: "Please enter your asset name",
        AssetLink: "URL of Photograph (if any)",
        AssetLinkPlaceholder: "Please enter url of your asset",
        AssetInfo: "Description of Photograph",
        AssetInfoPlaceholder:
            "Please provide a detailed description of your asset...",
        AssetCollectionName: "Collection Name (Optional)",
        AssetButton: "Tokenise your Photograph",
    },
    "real estate": {
        FieldTitle: "Upload File",
        AssetName: "Asset Name",
        AssetNamePlaceholder: "Please enter your asset name",
        AssetLink: "Url of asset (if any)",
        AssetLinkPlaceholder: "Please enter url of your asset",
        AssetInfo: "Asset Description",
        AssetInfoPlaceholder:
            "Please provide a detailed description of your asset...",
        AssetCollectionName: "Collection Name (Optional)",
        AssetButton: "Tokenise ",
    },
    "trading cards": {
        FieldTitle: "Upload File",
        AssetName: "Asset Name",
        AssetNamePlaceholder: "Please enter your asset name",
        AssetLink: "Url of asset (if any)",
        AssetLinkPlaceholder: "Please enter url of your asset",
        AssetInfo: "Asset Description",
        AssetInfoPlaceholder:
            "Please provide a detailed description of your asset...",
        AssetCollectionName: "Collection Name (Optional)",
        AssetButton: "Tokenise ",
    },
};
